services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image: yauchungki1305/washrooms-in-vancouver-parks:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64