name: milestone1
channels:
  - conda-forge
dependencies:
  - matplotlib=3.10.8
  - altair=6.0.0
  - pandas=2.3.3
  - conda-lock=3.0.4
  - python=3.13.9
  - jupyterlab=4.5.0
  - scikit-learn=1.7.2
  - pandera=0.26.1
  - deepchecks=0.3.2
