name: milestone1
channels:
  - conda-forge
dependencies:
  - matplotlib
  - altair
  - pandas
  - conda-lock
  - python
  - jupyterlab
  - scikit-learn
prefix: /Users/rebeccasokol-snyder/miniforge3/envs/milestone1
